version: "3.7"
services:
    app:
      restart: always
      build:
        context: .
        dockerfile: docker/APP
      environment:
        - LOG_LEVEL=DEBUG
    worker:
      restart: always
      build:
        context: .
        dockerfile: docker/WORKER
      environment:
        - LOG_LEVEL=DEBUG
      entrypoint: celery -A fsstalker.core.celery worker -B -Q check_posts,load_subreddits,notify,enforce_tiers -c 6 --uid=nobody --gid=nogroup -s /celery/celerybeat-schedule
      volumes:
        - /opt/bstsleuth:/celery