"""init

Revision ID: 4979c7e41fab
Revises: 
Create Date: 2021-01-27 21:13:34.987668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4979c7e41fab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('checked_post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('checked_at', sa.DateTime(), nullable=True),
    sa.Column('post_id', sa.String(length=6), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id')
    )
    op.create_table('notification_service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(length=20), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('watch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(length=20), nullable=False),
    sa.Column('subreddit', sa.String(length=21), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('include', sa.String(length=500), nullable=True),
    sa.Column('exclude', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_owner', 'watch', ['owner'], unique=False)
    op.create_index('idx_subreddit', 'watch', ['subreddit'], unique=False)
    op.create_table('sent_notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('triggered_post', sa.String(length=6), nullable=True),
    sa.Column('watch_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['watch_id'], ['watch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sent_notification')
    op.drop_index('idx_subreddit', table_name='watch')
    op.drop_index('idx_owner', table_name='watch')
    op.drop_table('watch')
    op.drop_table('notification_service')
    op.drop_table('checked_post')
    # ### end Alembic commands ###
