"""mod column

Revision ID: 5e9399906b28
Revises: bce0628e0adb
Create Date: 2022-09-17 13:04:13.307513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e9399906b28'
down_revision = 'bce0628e0adb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_mod', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_mod')
    # ### end Alembic commands ###
