"""add submission time

Revision ID: 92b4a00853ae
Revises: 5e9399906b28
Create Date: 2022-09-26 06:57:05.826519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92b4a00853ae'
down_revision = '5e9399906b28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sent_notification', sa.Column('submission_created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sent_notification', 'submission_created_at')
    # ### end Alembic commands ###
