"""more patreon

Revision ID: 9de7dbaa4fa7
Revises: d84125280904
Create Date: 2022-09-29 06:47:05.073293

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9de7dbaa4fa7'
down_revision = 'd84125280904'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('patreon_id', sa.String(length=30), nullable=True))
    op.drop_column('user', 'patreon_username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('patreon_username', mysql.VARCHAR(length=30), nullable=True))
    op.drop_column('user', 'patreon_id')
    # ### end Alembic commands ###
