"""add owner table

Revision ID: 9e2b76440343
Revises: f9e09b219d9e
Create Date: 2021-03-19 21:20:45.124130

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9e2b76440343'
down_revision = 'f9e09b219d9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_premium', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.add_column('notification_service', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notification_service', 'user', ['owner_id'], ['id'])
    op.drop_column('notification_service', 'owner')
    op.add_column('watch', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.drop_index('idx_owner', table_name='watch')
    op.create_foreign_key(None, 'watch', 'user', ['owner_id'], ['id'])
    op.drop_column('watch', 'owner')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watch', sa.Column('owner', mysql.VARCHAR(length=20), nullable=False))
    op.drop_constraint(None, 'watch', type_='foreignkey')
    op.create_index('idx_owner', 'watch', ['owner'], unique=False)
    op.drop_column('watch', 'owner_id')
    op.add_column('notification_service', sa.Column('owner', mysql.VARCHAR(length=20), nullable=False))
    op.drop_constraint(None, 'notification_service', type_='foreignkey')
    op.drop_column('notification_service', 'owner_id')
    op.drop_table('user')
    # ### end Alembic commands ###
