"""name columns

Revision ID: bce0628e0adb
Revises: 9e2b76440343
Create Date: 2021-03-20 07:38:41.384660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bce0628e0adb'
down_revision = '9e2b76440343'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_service', sa.Column('name', sa.String(length=200), nullable=False))
    op.create_unique_constraint(None, 'notification_service', ['url'])
    op.add_column('watch', sa.Column('name', sa.String(length=200), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watch', 'name')
    op.drop_constraint(None, 'notification_service', type_='unique')
    op.drop_column('notification_service', 'name')
    # ### end Alembic commands ###
