"""patreon changes

Revision ID: d84125280904
Revises: 92b4a00853ae
Create Date: 2022-09-28 19:56:58.336516

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd84125280904'
down_revision = '92b4a00853ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patreon_tiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('max_watches', sa.Integer(), nullable=False),
    sa.Column('max_notification_services', sa.Integer(), nullable=False),
    sa.Column('notify_delay', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('patreon_tier_id', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('patreon_username', sa.String(length=30), nullable=True))
    op.create_foreign_key(None, 'user', 'patreon_tiers', ['patreon_tier_id'], ['id'])
    op.drop_column('user', 'is_premium')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_premium', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'patreon_username')
    op.drop_column('user', 'patreon_tier_id')
    op.drop_table('patreon_tiers')
    # ### end Alembic commands ###
