"""watch to notificatoin

Revision ID: da7f431f8f56
Revises: 4979c7e41fab
Create Date: 2021-01-27 22:01:02.044139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da7f431f8f56'
down_revision = '4979c7e41fab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watch_to_notification',
    sa.Column('watch_id', sa.Integer(), nullable=True),
    sa.Column('notification_service_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['notification_service_id'], ['notification_service.id'], ),
    sa.ForeignKeyConstraint(['watch_id'], ['watch.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watch_to_notification')
    # ### end Alembic commands ###
