"""triggered word to sent notify

Revision ID: f9e09b219d9e
Revises: da7f431f8f56
Create Date: 2021-01-31 20:46:03.606628

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f9e09b219d9e'
down_revision = 'da7f431f8f56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sent_notification', sa.Column('triggered_word', sa.String(length=100), nullable=False))
    op.alter_column('sent_notification', 'triggered_post',
               existing_type=mysql.VARCHAR(length=6),
               nullable=False)
    op.alter_column('watch', 'include',
               existing_type=mysql.VARCHAR(length=500),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('watch', 'include',
               existing_type=mysql.VARCHAR(length=500),
               nullable=True)
    op.alter_column('sent_notification', 'triggered_post',
               existing_type=mysql.VARCHAR(length=6),
               nullable=True)
    op.drop_column('sent_notification', 'triggered_word')
    # ### end Alembic commands ###
